Fix missing sed

diff --git a/rootfs/etc/s6-overlay/s6-rc.d/xray-config/run b/rootfs/etc/s6-overlay/s6-rc.d/xray-config/run
--- a/rootfs/etc/s6-overlay/s6-rc.d/xray-config/run
+++ b/rootfs/etc/s6-overlay/s6-rc.d/xray-config/run
@@ -39,9 +39,7 @@ yq eval-all \
     -oj \
     > "${XRAY_SERVER_CONFIG}"
 sed -i \
-    -e "s|{{CERTBOT_LIVE_CERT_PATH}}|${CERTBOT_LIVE_CERT_PATH}|g" \
     -e "s|{{REALITY_DOMAIN}}|${REALITY_DOMAIN}|g" \
-    -e "s|{{XHTTP_DOMAIN}}|${XHTTP_DOMAIN}|g" \
     -e "s|{{XRAY_XHTTP_PATH}}|${XRAY_XHTTP_PATH}|g" \
     -e "s|{{XRAY_UUID}}|${XRAY_UUID}|g" \
     -e "s|{{XRAY_REALITY_PRIVATE_KEY}}|${XRAY_REALITY_PRIVATE_KEY}|g" \
@@ -60,7 +58,8 @@ fi
 
 # Get public IP
 if [ -z "${PUBLIC_IP:+x}" ]; then
-    PUBLIC_IP=$(wget -qO- api.ipify.org)
+    PUBLIC_IP=$(wget -qO- https://api.ipify.org)
+    [ -n "${PUBLIC_IP}" ] || { echo "Failed to determine PUBLIC_IP" >&2; exit 1; }
 fi
 
 # Pin the leaf certificates nginx serves. Clients use these hashes
